name: Create GitHub Release
description: 'Creates a GitHub Release'

inputs:
  tag:
    description: 'Git tag to release.'
    required: true
  version:
    description: 'Release version.'
    required: true
  prerelease:
    description: 'Mark the GitHub Release as a pre-release.'
    required: false
    default: 'false'
  body_path:
    description: 'Path to the release notes markdown file.'
    required: true

runs:
  using: composite
  steps:
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag }}
        name: ${{ inputs.version }}
        prerelease: ${{ inputs.prerelease }}
        body_path: ${{ inputs.body_path }}
        generate_release_notes: false
