/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/

import { readFile, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import process from "node:process";
import { URL, fileURLToPath } from "node:url";
import { iconNames } from "lucide-react/dynamic.js";
import { format, resolveConfig } from "prettier";

const repositoryRoot = fileURLToPath(new URL("../../..", import.meta.url));
const directory = resolve(repositoryRoot, "ui/src/icons");
const checkOnly = process.argv.includes("--check");
const prettierOptions = (await resolveConfig(join(directory, "icon-name.generated.ts"))) ?? {};
const sourceHeader = (await readFile(resolve(repositoryRoot, ".github/scripts/miaixz.org"), "utf8"))
  .replaceAll("\r\n", "\n")
  .trim();

const toPascalCase = (value) =>
  value
    .split("-")
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join("");

const toKebabCase = (value) =>
  value
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1-$2")
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Za-z])([0-9])/g, "$1-$2")
    .replace(/([0-9])([A-Za-z])/g, "$1-$2")
    .toLowerCase();

const dynamicNames = new Set(iconNames);
const miaixzNames = [...new Set(iconNames.map(toPascalCase))].sort();

const overrides = miaixzNames
  .map((name) => [name, iconNames.find((iconName) => toPascalCase(iconName) === name)])
  .filter((entry) => entry[1] !== undefined && !dynamicNames.has(toKebabCase(entry[0])));

const iconNamesSource = `${sourceHeader}

/*
 * Generated by .github/scripts/codegen/icon-names.mjs. Do not edit by hand.
 */

/**
 * Identifies every icon name supported by the active Miaixz icon provider.
 *
 * Names are a stable Miaixz public contract. Provider migrations must preserve them.
 *
 * @public
 */
export type MiaixzIconName =
${miaixzNames.map((name, index) => `  | "${name}"${index === miaixzNames.length - 1 ? ";" : ""}`).join("\n")}
`;

const overridesSource = `${sourceHeader}

/*
 * Generated by .github/scripts/codegen/icon-names.mjs. Do not edit by hand.
 */

import type { MiaixzIconName } from "./icon-name.generated.js";

/**
 * Resolves exceptional Miaixz names that cannot be converted to provider names mechanically.
 *
 * @internal
 */
export const miaixzIconNameOverrides: Readonly<Partial<Record<MiaixzIconName, string>>> =
  Object.freeze({
${overrides.map(([name, iconName]) => `    ${name}: "${iconName}",`).join("\n")}
  });
`;

const targets = new Map([
  [
    "icon-name.generated.ts",
    await format(iconNamesSource, { ...prettierOptions, parser: "typescript" }),
  ],
  [
    "icon-name-overrides.generated.ts",
    await format(overridesSource, { ...prettierOptions, parser: "typescript" }),
  ],
]);
const staleFiles = [];

for (const [fileName, source] of targets) {
  const path = join(directory, fileName);
  const current = await readFile(path, "utf8").catch(() => "");
  if (current === source) continue;
  if (checkOnly) staleFiles.push(fileName);
  else await writeFile(path, source, "utf8");
}

if (staleFiles.length > 0) {
  throw new Error(
    `Generated icon files are stale: ${staleFiles.join(", ")}. Run npm run icons:generate.`,
  );
}

if (!checkOnly) process.stdout.write(`Generated ${miaixzNames.length} Miaixz icon names.\n`);
