/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/

/**
 * Provides the generated, read-only format support manifest.
 */

import type { FormatManifestRecord } from "../shared/contracts/format.js";

/**
 * Generated from the audited open-file-viewer baseline format facts.
 */
export const formatManifest = [
  {
    extension: "jpg",
    mimeTypes: ["image/jpeg"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "jpeg",
    mimeTypes: ["image/jpeg"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "jfif",
    mimeTypes: ["image/jpeg"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "pjpe",
    mimeTypes: ["image/pjpeg"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "pjpeg",
    mimeTypes: ["image/pjpeg"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "png",
    mimeTypes: ["image/png"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "gif",
    mimeTypes: ["image/gif"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "webp",
    mimeTypes: ["image/webp"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "avif",
    mimeTypes: ["image/avif"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "jxl",
    mimeTypes: ["image/jxl"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "svg",
    mimeTypes: ["image/svg+xml"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "bmp",
    mimeTypes: ["image/bmp"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "ico",
    mimeTypes: ["image/x-icon"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "cur",
    mimeTypes: ["image/x-icon"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "tif",
    mimeTypes: ["image/tiff"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "tiff",
    mimeTypes: ["image/tiff"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "apng",
    mimeTypes: ["image/apng"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "heic",
    mimeTypes: ["image/heic"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "heif",
    mimeTypes: ["image/heif"],
    driver: "image",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P1",
  },
  {
    extension: "mp4",
    mimeTypes: ["video/mp4"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "mpg",
    mimeTypes: ["video/mpeg"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "mpeg",
    mimeTypes: ["video/mpeg"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "mpe",
    mimeTypes: ["video/mpeg"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "mpv",
    mimeTypes: ["video/mpv"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "webm",
    mimeTypes: ["video/webm"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "ogg",
    mimeTypes: ["audio/ogg"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "ogv",
    mimeTypes: ["video/ogg"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "mov",
    mimeTypes: ["video/quicktime"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "m4v",
    mimeTypes: ["video/x-m4v"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "avi",
    mimeTypes: ["video/x-msvideo"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "mkv",
    mimeTypes: ["video/x-matroska"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "flv",
    mimeTypes: ["video/x-flv"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "wmv",
    mimeTypes: ["video/x-ms-wmv"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "3gp",
    mimeTypes: ["video/3gpp"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "3g2",
    mimeTypes: ["video/3gpp2"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "m2ts",
    mimeTypes: ["video/mp2t"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "m3u8",
    mimeTypes: ["application/vnd.apple.mpegurl"],
    driver: "video",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "mp3",
    mimeTypes: ["audio/mpeg"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "wav",
    mimeTypes: ["audio/wav"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "aif",
    mimeTypes: ["audio/aiff"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "aiff",
    mimeTypes: ["audio/aiff"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "aifc",
    mimeTypes: ["audio/aiff"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "aac",
    mimeTypes: ["audio/aac"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "m4a",
    mimeTypes: ["audio/mp4"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "flac",
    mimeTypes: ["audio/flac"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "opus",
    mimeTypes: ["audio/opus"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "oga",
    mimeTypes: ["audio/ogg"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "weba",
    mimeTypes: ["audio/webm"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "amr",
    mimeTypes: ["audio/amr"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "mid",
    mimeTypes: ["audio/midi"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "midi",
    mimeTypes: ["audio/midi"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "caf",
    mimeTypes: ["audio/x-caf"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "au",
    mimeTypes: ["audio/basic"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "snd",
    mimeTypes: ["audio/basic"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "wma",
    mimeTypes: ["audio/x-ms-wma"],
    driver: "audio",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "pdf",
    mimeTypes: ["application/pdf"],
    driver: "pdf",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P5",
  },
  {
    extension: "epub",
    mimeTypes: ["application/epub+zip"],
    driver: "epub",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "xps",
    mimeTypes: ["application/vnd.ms-xpsdocument"],
    driver: "xps",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "oxps",
    mimeTypes: ["application/oxps"],
    driver: "xps",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "txt",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "lrc",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "log",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "env",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "gitignore",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "dockerignore",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "npmrc",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "yarnrc",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "pnpmrc",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "editorconfig",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "browserslistrc",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "prettierrc",
    mimeTypes: ["application/json"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "eslintrc",
    mimeTypes: ["application/json"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "stylelintrc",
    mimeTypes: ["application/json"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "conf",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "config",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "properties",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "lock",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "json",
    mimeTypes: ["application/json"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "jsonc",
    mimeTypes: ["application/json"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "json5",
    mimeTypes: ["application/json5"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "ipynb",
    mimeTypes: ["application/x-ipynb+json"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "jsonl",
    mimeTypes: ["application/x-ndjson"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "ndjson",
    mimeTypes: ["application/x-ndjson"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "xml",
    mimeTypes: ["application/xml"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "yaml",
    mimeTypes: ["text/yaml"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "yml",
    mimeTypes: ["text/yaml"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "csv",
    mimeTypes: ["text/csv"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "tsv",
    mimeTypes: ["text/tab-separated-values"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "md",
    mimeTypes: ["text/markdown"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "markdown",
    mimeTypes: ["text/markdown"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "mmd",
    mimeTypes: ["text/vnd.mermaid"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "mermaid",
    mimeTypes: ["text/vnd.mermaid"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "toml",
    mimeTypes: ["application/toml"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "ini",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "proto",
    mimeTypes: ["text/x-protobuf"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "tf",
    mimeTypes: ["text/x-hcl"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "tfvars",
    mimeTypes: ["text/x-hcl"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "hcl",
    mimeTypes: ["text/x-hcl"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "tex",
    mimeTypes: ["application/x-tex"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "latex",
    mimeTypes: ["application/x-tex"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "bib",
    mimeTypes: ["text/x-bibtex"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "gv",
    mimeTypes: ["text/vnd.graphviz"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "http",
    mimeTypes: ["message/http"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "css",
    mimeTypes: ["text/css"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "scss",
    mimeTypes: ["text/css"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "less",
    mimeTypes: ["text/css"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "js",
    mimeTypes: ["text/javascript"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "mjs",
    mimeTypes: ["text/javascript"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "cjs",
    mimeTypes: ["text/javascript"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "ts",
    mimeTypes: ["text/typescript"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "tsx",
    mimeTypes: ["text/typescript"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "jsx",
    mimeTypes: ["text/javascript"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "htm",
    mimeTypes: ["text/html"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "html",
    mimeTypes: ["text/html"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "vue",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "py",
    mimeTypes: ["text/x-python"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "java",
    mimeTypes: ["text/x-java-source"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "go",
    mimeTypes: ["text/x-go"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "rs",
    mimeTypes: ["text/rust"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "rb",
    mimeTypes: ["text/x-ruby"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "swift",
    mimeTypes: ["text/x-swift"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "kt",
    mimeTypes: ["text/x-kotlin"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "kts",
    mimeTypes: ["text/x-kotlin"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "scala",
    mimeTypes: ["text/x-scala"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "lua",
    mimeTypes: ["text/x-lua"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "r",
    mimeTypes: ["text/x-r"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "dart",
    mimeTypes: ["text/x-dart"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "svelte",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "astro",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "elm",
    mimeTypes: ["text/x-elm"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "ex",
    mimeTypes: ["text/x-elixir"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "exs",
    mimeTypes: ["text/x-elixir"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "clj",
    mimeTypes: ["text/x-clojure"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "cljs",
    mimeTypes: ["text/x-clojure"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "erl",
    mimeTypes: ["text/x-erlang"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "hrl",
    mimeTypes: ["text/x-erlang"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "fs",
    mimeTypes: ["text/x-fsharp"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "fsx",
    mimeTypes: ["text/x-fsharp"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "hs",
    mimeTypes: ["text/x-haskell"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "lhs",
    mimeTypes: ["text/x-haskell"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "php",
    mimeTypes: ["application/x-httpd-php"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "c",
    mimeTypes: ["text/x-c"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "cpp",
    mimeTypes: ["text/x-c++src"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "h",
    mimeTypes: ["text/x-c"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "hpp",
    mimeTypes: ["text/x-c++hdr"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "cs",
    mimeTypes: ["text/x-csharp"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "sql",
    mimeTypes: ["application/sql"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "sh",
    mimeTypes: ["application/x-sh"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "bash",
    mimeTypes: ["application/x-sh"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "zsh",
    mimeTypes: ["application/x-sh"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "fish",
    mimeTypes: ["application/x-sh"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "ps1",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "bat",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "cmd",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "dockerfile",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "nginxconf",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "gradle",
    mimeTypes: ["text/plain"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "graphql",
    mimeTypes: ["application/graphql"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "gql",
    mimeTypes: ["application/graphql"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "pem",
    mimeTypes: ["application/x-pem-file"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "crt",
    mimeTypes: ["application/x-x509-ca-cert"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "cer",
    mimeTypes: ["application/pkix-cert"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "ics",
    mimeTypes: ["text/calendar"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "vcf",
    mimeTypes: ["text/vcard"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "diff",
    mimeTypes: ["text/x-diff"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "patch",
    mimeTypes: ["text/x-diff"],
    driver: "text",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "geojson",
    mimeTypes: ["application/geo+json"],
    driver: "gis",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "topojson",
    mimeTypes: ["application/topo+json"],
    driver: "gis",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "kml",
    mimeTypes: ["application/vnd.google-earth.kml+xml"],
    driver: "gis",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "kmz",
    mimeTypes: ["application/vnd.google-earth.kmz"],
    driver: "gis",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "gpx",
    mimeTypes: ["application/gpx+xml"],
    driver: "gis",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "shp",
    mimeTypes: ["application/octet-stream"],
    driver: "gis",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "drawio",
    mimeTypes: ["application/vnd.jgraph.mxfile"],
    driver: "drawing",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P3",
  },
  {
    extension: "dio",
    mimeTypes: ["application/vnd.jgraph.mxfile"],
    driver: "drawing",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P3",
  },
  {
    extension: "xmind",
    mimeTypes: ["application/vnd.xmind.workbook"],
    driver: "xmind",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P3",
  },
  {
    extension: "excalidraw",
    mimeTypes: ["application/vnd.excalidraw+json"],
    driver: "drawing",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P3",
  },
  {
    extension: "tldraw",
    mimeTypes: ["application/json"],
    driver: "drawing",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P3",
  },
  {
    extension: "zip",
    mimeTypes: ["application/zip"],
    driver: "archive",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "rar",
    mimeTypes: ["application/vnd.rar"],
    driver: "archive",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "7z",
    mimeTypes: ["application/x-7z-compressed"],
    driver: "archive",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "tar",
    mimeTypes: ["application/x-tar"],
    driver: "archive",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "gz",
    mimeTypes: ["application/gzip"],
    driver: "archive",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "tgz",
    mimeTypes: ["application/gzip"],
    driver: "archive",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "bz2",
    mimeTypes: ["application/x-bzip2"],
    driver: "archive",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "xz",
    mimeTypes: ["application/x-xz"],
    driver: "archive",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "docx",
    mimeTypes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "docm",
    mimeTypes: ["application/vnd.ms-word.document.macroenabled.12"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "dotx",
    mimeTypes: ["application/vnd.openxmlformats-officedocument.wordprocessingml.template"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "dotm",
    mimeTypes: ["application/vnd.ms-word.template.macroenabled.12"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "dot",
    mimeTypes: ["application/msword"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "doc",
    mimeTypes: ["application/msword"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "rtf",
    mimeTypes: ["application/rtf"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "odt",
    mimeTypes: ["application/vnd.oasis.opendocument.text"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "fodt",
    mimeTypes: ["application/vnd.oasis.opendocument.text-flat-xml"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "wps",
    mimeTypes: ["application/vnd.ms-works"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "xlsx",
    mimeTypes: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "xltx",
    mimeTypes: ["application/vnd.openxmlformats-officedocument.spreadsheetml.template"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "xls",
    mimeTypes: ["application/vnd.ms-excel"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "xlt",
    mimeTypes: ["application/vnd.ms-excel"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "xlsm",
    mimeTypes: ["application/vnd.ms-excel.sheet.macroenabled.12"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "xltm",
    mimeTypes: ["application/vnd.ms-excel.template.macroenabled.12"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "xlsb",
    mimeTypes: ["application/vnd.ms-excel.sheet.binary.macroenabled.12"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "ods",
    mimeTypes: ["application/vnd.oasis.opendocument.spreadsheet"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "fods",
    mimeTypes: ["application/vnd.oasis.opendocument.spreadsheet-flat-xml"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "numbers",
    mimeTypes: ["application/vnd.apple.numbers"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "et",
    mimeTypes: ["application/vnd.ms-excel"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "pptx",
    mimeTypes: ["application/vnd.openxmlformats-officedocument.presentationml.presentation"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "pptm",
    mimeTypes: ["application/vnd.ms-powerpoint.presentation.macroenabled.12"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "ppsx",
    mimeTypes: ["application/vnd.openxmlformats-officedocument.presentationml.slideshow"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "ppsm",
    mimeTypes: ["application/vnd.ms-powerpoint.slideshow.macroenabled.12"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "potx",
    mimeTypes: ["application/vnd.openxmlformats-officedocument.presentationml.template"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "potm",
    mimeTypes: ["application/vnd.ms-powerpoint.template.macroenabled.12"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "ppt",
    mimeTypes: ["application/vnd.ms-powerpoint"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "pps",
    mimeTypes: ["application/vnd.ms-powerpoint"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "odp",
    mimeTypes: ["application/vnd.oasis.opendocument.presentation"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "fodp",
    mimeTypes: ["application/vnd.oasis.opendocument.presentation-flat-xml"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "key",
    mimeTypes: ["application/vnd.apple.keynote"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "dps",
    mimeTypes: ["application/vnd.ms-powerpoint"],
    driver: "office",
    upstreamLevel: "R2",
    targetLevel: "R4",
    milestone: "P4",
  },
  {
    extension: "eml",
    mimeTypes: ["message/rfc822"],
    driver: "email",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "msg",
    mimeTypes: ["application/vnd.ms-outlook"],
    driver: "email",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "mbox",
    mimeTypes: ["application/mbox"],
    driver: "email",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P3",
  },
  {
    extension: "ofd",
    mimeTypes: ["application/ofd"],
    driver: "ofd",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "gltf",
    mimeTypes: ["model/gltf+json"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "glb",
    mimeTypes: ["model/gltf-binary"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "stl",
    mimeTypes: ["model/stl"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "obj",
    mimeTypes: ["model/obj"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "3ds",
    mimeTypes: ["model/3ds"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "fbx",
    mimeTypes: ["application/vnd.autodesk.fbx"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "dae",
    mimeTypes: ["model/vnd.collada+xml"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "ply",
    mimeTypes: ["application/ply"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "3mf",
    mimeTypes: ["model/3mf"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "usdz",
    mimeTypes: ["model/vnd.usdz+zip"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "usdc",
    mimeTypes: ["model/vnd.usd"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "usda",
    mimeTypes: ["model/vnd.usd"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "usd",
    mimeTypes: ["model/vnd.usd"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "wrl",
    mimeTypes: ["model/vrml"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "vrml",
    mimeTypes: ["model/vrml"],
    driver: "model-3d",
    upstreamLevel: "R3",
    targetLevel: "R3",
    milestone: "P7",
  },
  {
    extension: "dxf",
    mimeTypes: ["image/vnd.dxf"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "dwg",
    mimeTypes: ["application/acad"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "dwf",
    mimeTypes: ["model/vnd.dwf"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "step",
    mimeTypes: ["model/step"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "stp",
    mimeTypes: ["model/step"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "iges",
    mimeTypes: ["application/iges"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "igs",
    mimeTypes: ["application/iges"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "ifc",
    mimeTypes: ["application/x-step"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "sat",
    mimeTypes: ["application/sat"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "sab",
    mimeTypes: ["application/sab"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "x_t",
    mimeTypes: ["application/x-parasolid"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "x_b",
    mimeTypes: ["application/x-parasolid"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "3dm",
    mimeTypes: ["model/vnd.3dm"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "skp",
    mimeTypes: ["application/vnd.sketchup.skp"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "sldprt",
    mimeTypes: ["application/sldworks"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "sldasm",
    mimeTypes: ["application/sldworks"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "gds",
    mimeTypes: ["application/vnd.gds"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "gdsii",
    mimeTypes: ["application/x-gdsii"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "oas",
    mimeTypes: ["application/vnd.oasis.layout"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "oasis",
    mimeTypes: ["application/vnd.oasis.layout"],
    driver: "cad",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P7",
  },
  {
    extension: "ttf",
    mimeTypes: ["font/ttf"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "otf",
    mimeTypes: ["font/otf"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "woff",
    mimeTypes: ["font/woff"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "woff2",
    mimeTypes: ["font/woff2"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "eot",
    mimeTypes: ["application/vnd.ms-fontobject"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "psd",
    mimeTypes: ["image/vnd.adobe.photoshop"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "psb",
    mimeTypes: ["image/vnd.adobe.photoshop"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "ai",
    mimeTypes: ["application/postscript"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "eps",
    mimeTypes: ["application/postscript"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "ps",
    mimeTypes: ["application/postscript"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "webarchive",
    mimeTypes: ["application/x-webarchive"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "sqlite",
    mimeTypes: ["application/vnd.sqlite3"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "sqlite3",
    mimeTypes: ["application/vnd.sqlite3"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "db",
    mimeTypes: ["application/vnd.sqlite3"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "wasm",
    mimeTypes: ["application/wasm"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "parquet",
    mimeTypes: ["application/vnd.apache.parquet"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
  {
    extension: "avro",
    mimeTypes: ["application/avro"],
    driver: "asset",
    upstreamLevel: "R2",
    targetLevel: "R2",
    milestone: "P6",
  },
] as const satisfies readonly FormatManifestRecord[];
