import {
  Building2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Diamond,
  File,
  Folder,
  FolderOpen,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LoaderCircle,
  Menu,
  Minus,
  Palette,
  Plus,
  RotateCcw,
  Search,
  ScrollText,
  Server,
  ServerCog,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Trash2,
  TriangleAlert,
  Upload,
  Workflow,
  X,
  type LucideIcon,
} from "lucide-react";

import type { MiaixzIconName } from "./icon-names.js";

/**
 * Maps the frozen Miaixz icon names to statically imported Lucide components.
 *
 * The frozen object prevents project code from mutating the shared registry. Project-specific
 * icons must be passed to `Icon` instead of extending this map at runtime.
 *
 * @internal
 */
export const miaixzIconRegistry = Object.freeze({
  Building2,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Diamond,
  File,
  Folder,
  FolderOpen,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LoaderCircle,
  Menu,
  Minus,
  Palette,
  Plus,
  RotateCcw,
  Search,
  ScrollText,
  Server,
  ServerCog,
  Settings,
  ShieldCheck,
  SlidersHorizontal,
  Trash2,
  TriangleAlert,
  Upload,
  Workflow,
  X,
} satisfies Readonly<Record<MiaixzIconName, LucideIcon>>);
