/*
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
 ~                                                                           ~
 ~ Copyright (c) 2015-2026 miaixz.org and other contributors.                ~
 ~                                                                           ~
 ~ Licensed under the Apache License, Version 2.0 (the "License");           ~
 ~ you may not use this file except in compliance with the License.          ~
 ~ You may obtain a copy of the License at                                   ~
 ~                                                                           ~
 ~      https://www.apache.org/licenses/LICENSE-2.0                          ~
 ~                                                                           ~
 ~ Unless required by applicable law or agreed to in writing, software       ~
 ~ distributed under the License is distributed on an "AS IS" BASIS,         ~
 ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  ~
 ~ See the License for the specific language governing permissions and       ~
 ~ limitations under the License.                                            ~
 ~                                                                           ~
 ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~
*/

/**
 * Generates every committed TypeScript artifact from reviewed icon assets.
 */

import { existsSync } from "node:fs";
import {
  copyFile,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rename,
  rm,
  writeFile,
} from "node:fs/promises";
import { tmpdir } from "node:os";
import { basename, dirname, join, relative, resolve } from "node:path";
import process from "node:process";

import { parseIconSvg, serializeSvgNode } from "../lib/svg-pipeline.mjs";
import { scanCoreIconNames } from "../quality/validate.mjs";

const packageRoot = process.cwd();
const packageManifest = JSON.parse(
  await readFile(resolve(packageRoot, "package.json"), "utf8"),
);
if (packageManifest.name !== "@miaixz/icons") {
  throw new Error("generate-icons.mjs must run from @miaixz/icons.");
}
const repositoryRoot = resolve(packageRoot, "../..");
const assetsRoot = resolve(packageRoot, "src/assets");
const generatedRoot = resolve(packageRoot, "src/autogen");
const arguments_ = process.argv.slice(2);
if (
  arguments_.some((argument) => argument !== "--check") ||
  arguments_.length > 1
) {
  throw new Error(
    "generate-icons.mjs accepts only an optional --check argument.",
  );
}
const checkMode = arguments_.includes("--check");
const header = `${await readFile(resolve(repositoryRoot, ".github/scripts/miaixz.org"), "utf8")}\n`;
const generatedNotice =
  "/**\n * @generated by .github/scripts/modules/icons/codegen/generate-icons.mjs. Do not edit.\n */\n\n";
const frozenToolchain = Object.freeze({
  "@babel/parser": "8.0.4",
  "@playwright/test": "1.62.1",
  pixelmatch: "7.2.0",
  pngjs: "7.0.0",
  "svg-path-bbox": "2.1.0",
  "svg-pathdata": "7.2.0",
  svgpath: "2.6.0",
  svgo: "4.1.0",
});

/**
 * Reads one JSON input.
 *
 * @param path Absolute input path.
 * @returns Parsed JSON value.
 */
async function readJson(path) {
  return JSON.parse(await readFile(path, "utf8"));
}

/**
 * Rejects any direct or installed tool version drift before generating bytes.
 *
 * @returns Promise completed when the frozen toolchain is exact.
 */
async function verifyToolchain() {
  const rootManifest = await readJson(resolve(repositoryRoot, "package.json"));
  for (const [name, version] of Object.entries(frozenToolchain)) {
    if (rootManifest.devDependencies?.[name] !== version) {
      throw new Error(
        `${name} must be pinned to ${version} in root devDependencies.`,
      );
    }
    const installed = await readJson(
      resolve(repositoryRoot, "node_modules", name, "package.json"),
    );
    if (installed.version !== version) {
      throw new Error(
        `${name} installed version ${installed.version} does not match ${version}.`,
      );
    }
  }
}

/**
 * Formats one generated TypeScript module with the repository header.
 *
 * @param body TypeScript module body.
 * @returns Complete generated module text.
 */
function moduleText(body) {
  return `${header}${generatedNotice}${body.trim()}\n`;
}

/**
 * Converts a public icon name to its frozen constant key.
 *
 * @param name Public icon name.
 * @returns Constant object key.
 */
function constantKey(name) {
  return name.replaceAll("-", "_").toUpperCase();
}

/**
 * Encodes an exact ASCII name set as a prefix-factored regular expression.
 *
 * @param {string[]} names Sorted canonical names.
 * @returns {string} Regex source without anchors.
 */
function exactNamePattern(names) {
  const root = { terminal: false, children: new Map() };
  for (const name of names) {
    let node = root;
    for (const character of name) {
      let child = node.children.get(character);
      if (child === undefined) {
        child = { terminal: false, children: new Map() };
        node.children.set(character, child);
      }
      node = child;
    }
    node.terminal = true;
  }
  const encode = (node) => {
    const alternatives = [...node.children].map(
      ([character, child]) => `${character}${encode(child)}`,
    );
    const descendants =
      alternatives.length === 0
        ? ""
        : alternatives.length === 1
          ? alternatives[0]
          : `(?:${alternatives.join("|")})`;
    return node.terminal && descendants !== ""
      ? `(?:${descendants})?`
      : descendants;
  };
  return encode(root);
}

/**
 * Sorts object keys recursively for deterministic definition serialization.
 *
 * @param value JSON-compatible input.
 * @returns A deeply key-sorted copy.
 */
function stableValue(value) {
  if (Array.isArray(value)) return value.map(stableValue);
  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value)
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([key, child]) => [key, stableValue(child)]),
    );
  }
  return value;
}

/**
 * Recursively lists committed generated files.
 *
 * @param directory Directory to traverse.
 * @returns Relative generated paths.
 */
async function listFiles(directory) {
  if (!existsSync(directory)) return [];
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const path = resolve(directory, entry.name);
      return entry.isDirectory()
        ? listFiles(path)
        : [relative(generatedRoot, path)];
    }),
  );
  return nested.flat().filter((path) => !path.endsWith(".gitkeep"));
}

/**
 * Writes generated bytes to an OS temporary directory before touching official output.
 * Each destination file is then replaced with a same-directory rename, which is atomic
 * even when the workspace and the operating-system temporary directory are on different
 * filesystems.
 *
 * @param outputs Relative output paths and complete contents.
 * @returns Promise completed after comparison or replacement.
 */
async function commitGeneratedOutputs(outputs) {
  const stagingRoot = await mkdtemp(join(tmpdir(), "miaixz-icons-generate-"));
  try {
    for (const [path, content] of outputs) {
      const staged = resolve(stagingRoot, path);
      await mkdir(dirname(staged), { recursive: true });
      await writeFile(staged, content);
    }
    if (
      process.env.NODE_ENV === "test" &&
      process.env.MIAIXZ_ICON_GENERATOR_FAILURE === "after-stage"
    ) {
      throw new Error("Injected icon generator failure after staging.");
    }

    const existing = await listFiles(generatedRoot);
    const failures = [];
    if (checkMode) {
      for (const path of outputs.keys()) {
        const official = resolve(generatedRoot, path);
        const staged = resolve(stagingRoot, path);
        if (
          !existsSync(official) ||
          (await readFile(official, "utf8")) !==
            (await readFile(staged, "utf8"))
        ) {
          failures.push(path);
        }
      }
      failures.push(...existing.filter((path) => !outputs.has(path)));
    } else {
      for (const path of outputs.keys()) {
        const official = resolve(generatedRoot, path);
        const pending = resolve(
          dirname(official),
          `.${basename(official)}.${process.pid}.tmp`,
        );
        await mkdir(dirname(official), { recursive: true });
        try {
          await copyFile(resolve(stagingRoot, path), pending);
          await rename(pending, official);
        } finally {
          await rm(pending, { force: true });
        }
      }
      for (const path of existing) {
        if (!outputs.has(path))
          await rm(resolve(generatedRoot, path), { force: true });
      }
    }
    if (failures.length > 0) {
      throw new Error(
        `Generated icon files are stale: ${failures.sort().join(", ")}`,
      );
    }
  } finally {
    await rm(stagingRoot, { force: true, recursive: true });
  }
}

await verifyToolchain();

const catalogFile = await readJson(resolve(assetsRoot, "catalog.json"));
const releasePlan = await readJson(resolve(assetsRoot, "release-plan.json"));
const fixture = await readJson(
  resolve(packageRoot, "tests/fixtures/icon-names-0.6.5.json"),
);
const catalog = catalogFile.icons;
const catalogByName = new Map(catalog.map((entry) => [entry.name, entry]));
const aliases = new Map(
  catalog.flatMap((entry) => entry.aliases.map((alias) => [alias, entry.name])),
);
const publicNames = [
  ...new Set([
    ...catalog
      .filter(
        (entry) => entry.status === "stable" || entry.status === "deprecated",
      )
      .flatMap((entry) => [entry.name, ...entry.aliases]),
    ...fixture,
  ]),
].sort();
const keys = new Map();
for (const name of publicNames) {
  const key = constantKey(name);
  if (keys.has(key))
    throw new Error(`ICON_NAMES key collision: ${name} and ${keys.get(key)}.`);
  keys.set(key, name);
}

const definitions = new Map();
for (const entry of catalog) {
  if (
    entry.source !== "miaixz" ||
    !["stable", "deprecated"].includes(entry.status)
  )
    continue;
  for (const [variant, sizes] of Object.entries(entry.variants)) {
    for (const opticalSize of sizes) {
      const key = `${variant}/${opticalSize}/${entry.name}`;
      const sourcePath = resolve(assetsRoot, "svg", `${key}.svg`);
      const source = await readFile(sourcePath, "utf8");
      definitions.set(
        key,
        parseIconSvg(
          source,
          variant,
          relative(repositoryRoot, sourcePath),
          "miaixz",
        ),
      );
    }
  }
}

const expected = new Map();
const nameUnion = publicNames.map((name) => JSON.stringify(name)).join(" | ");
expected.set("names.ts", moduleText(`export type IconName = ${nameUnion};`));
const publicNameToCanonical = Object.fromEntries(
  publicNames.map((name) => [name, aliases.get(name) ?? name]),
);
const stableBuiltinNames = catalog
  .filter(
    (entry) =>
      entry.source === "miaixz" &&
      entry.status === "stable" &&
      entry.variants.outline?.includes("standard"),
  )
  .map((entry) => entry.name)
  .sort();
const canonicalNames = catalog.map((entry) => entry.name);
let stablePrefixLength = 0;
while (stableBuiltinNames.includes(canonicalNames[stablePrefixLength]))
  stablePrefixLength += 1;
const stablePrefixLast = canonicalNames[stablePrefixLength - 1];
const stableExceptions = stableBuiltinNames.filter(
  (name) => name > stablePrefixLast,
);
expected.set(
  "configuration.ts",
  moduleText(`
import type { IconName } from "./names.js";
const canonicalNamePattern = /^(?:${exactNamePattern(canonicalNames)})$/u;
const stablePrefixLast = ${JSON.stringify(stablePrefixLast)};
const stableExceptionPattern = /^(?:${exactNamePattern(stableExceptions)})$/u;
export function isCanonicalIconName(value: unknown): value is IconName {
  return typeof value === "string" && canonicalNamePattern.test(value);
}
export function isStableBuiltinIconName(value: unknown): value is IconName {
  return isCanonicalIconName(value) && (value <= stablePrefixLast || stableExceptionPattern.test(value));
}
`),
);
const constants = Object.fromEntries(
  [...keys].map(([key, name]) => [key, name]),
);
expected.set(
  "catalog.ts",
  moduleText(`
export type IconCategory = ${["actions", "navigation", "status", "files", "editor", "media", "communication", "commerce", "devices", "maps", "data", "objects"].map(JSON.stringify).join(" | ")};
export type IconTier = "core" | "extended" | "compat";
export type IconStatus = "draft" | "review" | "stable" | "deprecated";
export interface IconCatalogEntry {
  readonly name: string;
  readonly category: IconCategory;
  readonly tier: IconTier;
  readonly status: IconStatus;
  readonly source: "miaixz" | "third-party";
  readonly tags: readonly string[];
  readonly aliases: readonly string[];
  readonly replacement: string | null;
  readonly variants: Readonly<Partial<Record<"outline" | "filled", readonly ("compact" | "standard" | "display")[]>>>;
  readonly rtl: "none" | "mirror";
  readonly introducedIn: string;
}
export interface ParseIconNameOptions {
  readonly fallback?: import("./names.js").IconName;
  readonly onInvalid?: (value: unknown) => void;
}
export const ICON_NAMES = Object.freeze(${JSON.stringify(constants, null, 2)} as const satisfies Readonly<Record<string, import("./names.js").IconName>>);
export const iconCatalog = Object.freeze(JSON.parse(${JSON.stringify(JSON.stringify(catalog))}) as IconCatalogEntry[]);
const canonicalByPublicName = Object.freeze(${JSON.stringify(publicNameToCanonical, null, 2)}) as Readonly<Record<string, import("./names.js").IconName>>;
const entryByCanonicalName = new Map(iconCatalog.map((entry) => [entry.name, entry]));
export function isIconName(value: unknown): value is import("./names.js").IconName {
  return typeof value === "string" && Object.hasOwn(canonicalByPublicName, value);
}
export function toCanonicalIconName(name: import("./names.js").IconName): import("./names.js").IconName {
  return canonicalByPublicName[name]!;
}
export function getIconCatalogEntry(name: import("./names.js").IconName): IconCatalogEntry | undefined {
  return entryByCanonicalName.get(toCanonicalIconName(name));
}
export function parseIconName(value: unknown, options: ParseIconNameOptions = {}): import("./names.js").IconName {
  const fallback = options.fallback ?? "help";
  if (!isIconName(fallback)) throw new TypeError(\`[miaixz] Invalid icon fallback "\${String(fallback)}".\`);
  if (isIconName(value)) return toCanonicalIconName(value);
  options.onInvalid?.(value);
  return toCanonicalIconName(fallback);
}
`),
);

const shardIds = [
  "core-ui",
  "actions",
  "navigation",
  "status",
  "files",
  "editor",
  "media",
  "communication",
  "commerce",
  "devices",
  "maps",
  "data",
  "objects",
];
const shardEntries = new Map(shardIds.map((id) => [id, []]));
const definitionIndex = {};
for (const [key, definition] of definitions) {
  const name = key.split("/")[2];
  const entry = catalogByName.get(name);
  const shardId = entry.tier === "core" ? "core-ui" : entry.category;
  shardEntries.get(shardId).push([key, definition]);
  definitionIndex[key] = shardId;
  expected.set(
    `definitions/${key}.ts`,
    moduleText(
      `import type { IconDefinition } from "../../../../definitions/icon-definition.js";\nconst definition: IconDefinition = ${JSON.stringify(stableValue(definition), null, 2)};\nexport default definition;`,
    ),
  );
}
const runtimeEntries = Object.fromEntries(
  Object.entries(publicNameToCanonical).map(([name, canonical]) => {
    const entry = catalogByName.get(canonical);
    return [name, [canonical, entry.rtl]];
  }),
);
expected.set(
  "runtime-catalog.ts",
  moduleText(`
import type { IconName } from "./names.js";
const entries: Readonly<Record<string, readonly [IconName, "none" | "mirror"]>> = Object.freeze(${JSON.stringify(runtimeEntries)});
const definitionIndex: Readonly<Record<string, string>> = Object.freeze(${JSON.stringify(definitionIndex)});
export function getRuntimeIconEntry(value: unknown): readonly [IconName, "none" | "mirror"] | undefined {
  return typeof value === "string" ? entries[value] : undefined;
}
export function getBuiltinDefinitionShard(name: IconName, variant: string, opticalSize: string): string | undefined {
  return definitionIndex[\`\${variant}/\${opticalSize}/\${name}\`];
}
`),
);
for (const [shardId, entries] of shardEntries) {
  if (entries.length === 0) continue;
  expected.set(
    `shards/${shardId}.ts`,
    moduleText(
      `import type { IconDefinition } from "../../definitions/icon-definition.js";\nexport const definitions: Readonly<Record<string, IconDefinition>> = Object.freeze(${JSON.stringify(Object.fromEntries(entries.map(([key, value]) => [key, stableValue(value)])), null, 2)});`,
    ),
  );
}
const importCases = [...shardEntries]
  .filter(([, entries]) => entries.length > 0)
  .map(
    ([id]) =>
      `    case ${JSON.stringify(id)}: return import(${JSON.stringify(`./shards/${id}.js`)});`,
  )
  .join("\n");
const coverage = { core: 0, extended: 0, compat: 0, total: 0 };
for (const entry of catalog.filter(
  (item) => item.source === "miaixz" && item.status === "stable",
)) {
  coverage[entry.tier] += 1;
  coverage.total += 1;
}
expected.set(
  "manifest.ts",
  moduleText(
    `import type { IconProviderManifest } from "../runtime/provider.js";\nexport const miaixzManifest = Object.freeze(${JSON.stringify({ schemaVersion: 2, id: "miaixz", packageName: "@miaixz/icons", packageVersion: "0.6.5", source: "miaixz", license: "Apache-2.0", sources: [], coverage: { outline: coverage }, variants: ["outline"], opticalSizes: ["standard"] }, null, 2)} as const satisfies IconProviderManifest);`,
  ),
);
expected.set(
  "provider.ts",
  moduleText(`
import { miaixzManifest } from "./manifest.js";
import { assertIconDefinition } from "../definitions/validate-definition.js";
import type { IconDefinition } from "../definitions/icon-definition.js";
import type { IconProvider, IconRequest } from "../runtime/provider.js";
const shardCache = new Map<string, Promise<{ readonly definitions: Readonly<Record<string, IconDefinition>> }>>();
function importShard(id: string) {
  switch (id) {
${importCases}
    default: return Promise.reject(new TypeError(\`[miaixz] Unknown icon shard "\${id}".\`));
  }
}
function loadShard(id: string) {
  const cached = shardCache.get(id);
  if (cached) return cached;
  const pending = importShard(id);
  shardCache.set(id, pending);
  return pending;
}
async function load(request: IconRequest): Promise<IconDefinition | null> {
  const runtimeCatalog = await import("./runtime-catalog.js");
  const entry = runtimeCatalog.getRuntimeIconEntry(request.name);
  if (entry === undefined) return null;
  const name = entry[0];
  const key = \`\${request.variant}/\${request.opticalSize}/\${name}\`;
  const shard = runtimeCatalog.getBuiltinDefinitionShard(name, request.variant, request.opticalSize);
  if (shard === undefined) return null;
  const module = await loadShard(shard);
  const definition = module.definitions[key];
  return definition === undefined ? null : assertIconDefinition(definition);
}
export const miaixzProvider: IconProvider = Object.freeze({
  manifest: miaixzManifest,
  load,
  async preload(requests: readonly IconRequest[]) {
    await Promise.all(requests.map(load));
  },
});
`),
);

/**
 * Builds one offline Iconify collection from stable original definitions.
 *
 * @param {"outline" | "filled"} variant Collection variant.
 * @returns Complete Iconify collection.
 */
const iconifyFor = (variant) => {
  const icons = {};
  const iconAliases = {};
  for (const entry of catalog.filter(
    (item) => item.source === "miaixz" && item.status === "stable",
  )) {
    const definition = definitions.get(`${variant}/standard/${entry.name}`);
    if (!definition) continue;
    const paint =
      variant === "outline"
        ? 'fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round"'
        : 'fill="currentColor" stroke="none"';
    icons[entry.name] = {
      body: `<g ${paint}>${definition.nodes.map(serializeSvgNode).join("")}</g>`,
    };
    for (const alias of entry.aliases)
      iconAliases[alias] = { parent: entry.name };
  }
  return {
    prefix: variant === "outline" ? "miaixz" : "miaixz-filled",
    width: 24,
    height: 24,
    icons,
    aliases: iconAliases,
  };
};
expected.set(
  "iconify-outline.ts",
  moduleText(
    `const collection = ${JSON.stringify(iconifyFor("outline"), null, 2)} as const;\nexport default collection;`,
  ),
);
expected.set(
  "iconify-filled.ts",
  moduleText(
    `const collection = ${JSON.stringify(iconifyFor("filled"), null, 2)} as const;\nexport default collection;`,
  ),
);
const coreUsage = scanCoreIconNames(repositoryRoot).map(([name, location]) => ({
  name,
  location,
}));
expected.set(
  "generation-report.json",
  `${JSON.stringify({ schemaVersion: 1, release: releasePlan.release, state: releasePlan.state, canonicalDefinitions: definitions.size, publicNames: publicNames.length, coreUsage }, null, 2)}\n`,
);

await commitGeneratedOutputs(expected);
console.log(
  checkMode
    ? "Generated icon files are current."
    : `Generated ${expected.size} icon files.`,
);
